language: cpp
compiler: gcc
dist: trusty

install:
  # Qwt
  - sudo apt-get install -qq libqwt5-qt4-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp11_qt4_qwt

after_failure:
  - apt-cache search libqwt
  - cd /usr/include
  - find . -name qwt_plot.h